sessionDir: "/mnt/user/appdata/rutorrent/rtorrent/rtorrent_sess"
rootTorrentsDir: "/mnt/user"
torrentsSubdirs:
  - "torrents-animation"
  - "torrents-animation-lib"
  - "torrents-ebook"
  - "torrents-ebook-lib"
  - "torrents-iso"
  - "torrents-iso-lib"
  - "torrents-movie"
  - "torrents-movie-lib"
  - "torrents-music"
  - "torrents-music-lib"
  - "torrents-software"
  - "torrents-software-lib"
  - "torrents-tv"
  - "torrents-tv-lib"
  - "torrents-downloads"
